### PR TITLE
lastError() added and config reading and writing fixed

### PR DESCRIPTION
**Pull request by AlinaNova21**
Added lastError(), returns 0 if the last call returned +ok. Also fixed readConfig and writeConfig (readConfig works now, writeConfig is untested as I'm not sure how brick proof these wifi modules are)

### CODE REVIEW

**Comment by digistump** [comment]
they are pretty hard to brick - if you look at the datasheet there is a pin you can pull high to put it back into factory default mode

**Comment by AlinaNova21** [comment]
Thats nice to know, I will probably test the writeConfig function tomorrow, I hadn't looked at that part of the datasheet, I had just focused on the AT command reference. How many of those pins are actually connected?

**Comment by digistump** [comment]
Not many - checkout the schematic in the comments on kickstarter - by
memory RTS, CTS, TX, RX, 3.3v, GND and reset

**Comment by AlinaNova21** [comment]
I just wish the stock Serial library supported hardware flow control :/

**Comment by digistump** [comment]
Me to - I messed with some hacked together flow control but it didn't work
and production stuff pulled me back away from it.

**Comment by AlinaNova21** [comment]
How are the CTS and RTS wired on the wifi module? its CTS<-RTS and RTS->CTS right? 
I've found the values to change that SHOULD enable hardware flow control on the SAM3X, but am trying to make sure  of what flow control method the wifi is using. And is the hardware RTS/CTS on Serial1 wired to 104/105?

**Comment by digistump** [comment]
SAM3X RTS -> WiFi CTS = PC20
SAM3X CTS -> WiFi RTS = PC27

**Comment by digistump** [comment]
Correction:
SAM3X CTS <- WiFi RTS = PC20 Pin 105
SAM3X RTS -> WiFi CTS = PC27 Pin 104

**Comment by AlinaNova21** [comment]
Good news, I have got working software based flow control, I'm now able to
load a large webpage at 115200 baud without corruption from full buffers. :)
The only big annoyance I see is that I disable Serial1 in variant.h and
variant.cpp and create it in DigiFi with a modified copy of USARTClass and
RingBuffer (Ringbuffer originally uses a 64 byte buffer! I bumped that to
2048 in the copy) This is only doing flow control on the receiving side,
but most of the time wifi is going to send faster than the sam3x can send
to it.
I'm going to try and get it to where it doesn't require a modified
variant.h and cpp, just not sure what direction is best here.

Adam

**Comment by digistump** [comment]
Awesome

It would be great if the variant changes weren't needed but if they were we
could at compile time select whether to make them or not.

The only use case for exceeding the rx buffer on the wifi is posting large
pieces of data, like a photo from a serial camera - but certainly by far
the most common use case will be large amounts of received data, so this is
wonderful!

Thanks for all of your great work on this Adam! If you decide to keep
working this I'll make sure to send you some more stuff, as it is the least
I can do to show my thanks for contributing!

**Comment by AlinaNova21** [comment]
In the last commit (https://github.com/ags131/DigiFi/commit/9c19997118d46272ef5ea58acaa278f5b2d47ffc) I made, I've got it down to only one change in variant.cpp, if I can find a way to remap that interrupt it shouldn't require any changes. I tried just wrapping it in a #ifndef DigiFi_h but that always ran before DigiFi.h was loaded.

**Comment by digistump** [comment]
I guess that makes sense because variants/core/etc all get included before
the sketch...

**Comment by AlinaNova21** [comment]
And after some testing, it seems there is only slight speed benefit from a larger buffer as long as its read from the buffer quickly. Although a larger buffer means more can be received before it pauses the receiving.
It will work on the standard 64 byte buffer, so the DigiFiRingBuffer in my current copy isn't necessarily needed.

**Comment by AlinaNova21** [comment]
Interesting, the wifi module also works with baud rates upto 460800. 460800 actually pulls data fairly quickly for me.

**Comment by digistump** [comment]
We picked the module because the baud rates can go so high - I believe it
unofficially supports even higher than that or if not yet, then will with
future firmware

**Comment by AlinaNova21** [comment]
I couldn't get it to accept any higher, they may add that in future firmware. I also noticed that most webservers do not close the tcp stream after responding. so multiple requests can be made from the same connection.

**Comment by digistump** [comment]
I was just thinking - if it can't be done without changing variant then I
can just make two board options "DigiX (Standard)" and "DigiX (w/ DigiFi
HFC)" in the tools->board menu

**Comment by AlinaNova21** [comment]
Commit https://github.com/ags131/DigiFi/commit/853a11a1f037cf1427306715bd1f3f4b4765e5cd has a USARTClass that can be dropped in sam/cores. It should work without modifying variant and still allows flow control to be optional. There is a setFlowControl(bool) function to enable flow control. I plan to adjust it to where the pins are not hardcoded, but forgot my DigiX at home today so can't test anything. :/

**Comment by digistump** [comment]
That is great - thanks again! Do you want me to send you another DigiX so
you can have one for the road and one for home? That way you won't have to
worry about bricking your only one.

**Comment by AlinaNova21** [comment]
That would be cool! I won't be able to do much in the next couple of weeks, end of September gets really busy at work. After that when things settle down I will definitely be messing with it more. Are there any good cheap nRF breakout boards you recommend? I tried creating one on a digispark proto shield but my soldering skills fail me it that tight of a confined space. I also plan to network my Uno and Pi.

**Comment by digistump** [comment]
Do you feel the changes up to this point are ready to merge in?

I sent you another DigiX, if nothing else to thank you for all you've done
on this library. No great nRF breakout boards I've used - I usually
breadboard with them using one of those mini breadboards - the Digispark
Pro (coming soon) will have a shield for them - which will leave the normal
Digispark pins open for other shields.

**Comment by AlinaNova21** [comment]
Should be, I believe everything is working at the moment, haven't had a free time to check yet. The USARTClass files would go in core to be able to work without variant hacking, they have an added enableCTS(bool) and setCTSPin(int).
All these changes are currently in the flowcontrol branch.

**Comment by digistump** [comment]
If you have a chance can you send a pull request from that branch - to keep
it all clean and linked (or maybe because I'm just missing how I can do
that...)?

Thanks,
Erik

**Comment by AlinaNova21** [comment]
Sure, will do that right now :)

**Pull request merged**
